theme: hugo-theme-stack
defaultContentLanguage: zh-cn
title: Braindance
baseURL: https://www.braindance.top

services:
  # GA Tracking ID
  googleAnalytics:
    id: G-0CQLT1ENWK

pagination:
  pagerSize: 5

permalinks:
  page:
    posts: /articles/:year/:month/:slug/
    page: /:slug/

params:
  description: ä¸ºä¸–ç•Œä¸Šæ‰€æœ‰çš„ç¾Žå¥½è€Œæˆ˜
  mainSections: posts
  favicon: /favicon.ico
  Sidebar:
    compact: false
    emoji: ðŸ¥¸
    subtitle: å…´è¶£ä½¿ç„¶
    avatar:
      enabled: true
      src: img/avatar.png
      local: true
  Footer:
    since: 2020
  Article:
    toc: true
    readingTime: true
    license:
      enabled: true
  Comments:
    enabled: true
    provider: twikoo
    twikoo:
      envId: https://twikoo.braindance.top/
  colorScheme:
    toggle: true
    default: auto
  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 3
      - type: categories
        params:
          limit: 5
      - type: tag-cloud
        params:
          limit: 5
    page:
      - type: toc
  # imageProcessing:
  #   cover:
  #     enabled: true
  #   content:
  #     enabled: true

social:
  - identifier: github
    name: GitHub
    url: https://github.com/penginman
    params:
      icon: brand-github
      newTab: true

menu:
  main:
    - name: Home
      pageRef: /
      weight: 1
      params:
        icon: home
    - name: Archives
      pageRef: /posts
      weight: 2
      params:
        icon: archives
    - name: Tags
      pageRef: /tags
      weight: 3
      params:
        icon: tag
    - name: Links
      pageRef: /links
      weight: 4
      params:
        icon: friends
    - name: Travelling
      url: https://www.travellings.cn/go.html
      weight: 5
      params:
        icon: travelling-light
        newTab: true
outputs:
  page:
    - HTML
    - RSS
    - JSON

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

markup:
  goldmark:
    extensions:
      passthrough:
        enable: true
        delimiters:
          block:
            - - \[
              - \]
            - - $$
              - $$
          inline:
            - - \(
              - \)
    renderer:
      ## Set to true if you have HTML content inside Markdown
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
